./apps/testHCRF/hcrfTest -t -TT -F "WordCnt" -d ./data/zhtNewsTopic2_dataTrain.csv -l ./data/zhtNewsTopic2_seqLabelTrain.csv -D ./data/zhtNewsTopic2_dataTest.csv -L ./data/zhtNewsTopic2_seqLabelTest.csv -C ./data/zhtNewsTopic2_corpus.txt -S ./data/zhtNewsTopic2_sentiDict.txt -m ./result/zhtNewsTopic2_wordCnt.model -r ./result/zhtNewsTopic2_wordCnt.result -c ./result/zhtNewsTopic2_wordCnt.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur" -d ./data/zhtNewsTopic2_dataTrain.csv -l ./data/zhtNewsTopic2_seqLabelTrain.csv -D ./data/zhtNewsTopic2_dataTest.csv -L ./data/zhtNewsTopic2_seqLabelTest.csv -C ./data/zhtNewsTopic2_corpus.txt -S ./data/zhtNewsTopic2_sentiDict.txt -m ./result/zhtNewsTopic2_wordOccur.model -r ./result/zhtNewsTopic2_wordOccur.result -c ./result/zhtNewsTopic2_wordOccur.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur PosWordOccur NegWordOccur PosLNeg PosL2Neg NegLPos NegL2Pos PosEqualNeg" -d ./data/zhtNewsTopic2_dataTrain.csv -l ./data/zhtNewsTopic2_seqLabelTrain.csv -D ./data/zhtNewsTopic2_dataTest.csv -L ./data/zhtNewsTopic2_seqLabelTest.csv -C ./data/zhtNewsTopic2_corpus.txt -S ./data/zhtNewsTopic2_sentiDict.txt -m ./result/zhtNewsTopic2_paper.model -r ./result/zhtNewsTopic2_paper.result -c ./result/zhtNewsTopic2_paper.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordCnt" -d ./data/zhtNewsTopic3_dataTrain.csv -l ./data/zhtNewsTopic3_seqLabelTrain.csv -D ./data/zhtNewsTopic3_dataTest.csv -L ./data/zhtNewsTopic3_seqLabelTest.csv -C ./data/zhtNewsTopic3_corpus.txt -S ./data/zhtNewsTopic3_sentiDict.txt -m ./result/zhtNewsTopic3_wordCnt.model -r ./result/zhtNewsTopic3_wordCnt.result -c ./result/zhtNewsTopic3_wordCnt.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur" -d ./data/zhtNewsTopic3_dataTrain.csv -l ./data/zhtNewsTopic3_seqLabelTrain.csv -D ./data/zhtNewsTopic3_dataTest.csv -L ./data/zhtNewsTopic3_seqLabelTest.csv -C ./data/zhtNewsTopic3_corpus.txt -S ./data/zhtNewsTopic3_sentiDict.txt -m ./result/zhtNewsTopic3_wordOccur.model -r ./result/zhtNewsTopic3_wordOccur.result -c ./result/zhtNewsTopic3_wordOccur.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur PosWordOccur NegWordOccur PosLNeg PosL2Neg NegLPos NegL2Pos PosEqualNeg" -d ./data/zhtNewsTopic3_dataTrain.csv -l ./data/zhtNewsTopic3_seqLabelTrain.csv -D ./data/zhtNewsTopic3_dataTest.csv -L ./data/zhtNewsTopic3_seqLabelTest.csv -C ./data/zhtNewsTopic3_corpus.txt -S ./data/zhtNewsTopic3_sentiDict.txt -m ./result/zhtNewsTopic3_paper.model -r ./result/zhtNewsTopic3_paper.result -c ./result/zhtNewsTopic3_paper.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordCnt" -d ./data/zhtNewsTopic4_dataTrain.csv -l ./data/zhtNewsTopic4_seqLabelTrain.csv -D ./data/zhtNewsTopic4_dataTest.csv -L ./data/zhtNewsTopic4_seqLabelTest.csv -C ./data/zhtNewsTopic4_corpus.txt -S ./data/zhtNewsTopic4_sentiDict.txt -m ./result/zhtNewsTopic4_wordCnt.model -r ./result/zhtNewsTopic4_wordCnt.result -c ./result/zhtNewsTopic4_wordCnt.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur" -d ./data/zhtNewsTopic4_dataTrain.csv -l ./data/zhtNewsTopic4_seqLabelTrain.csv -D ./data/zhtNewsTopic4_dataTest.csv -L ./data/zhtNewsTopic4_seqLabelTest.csv -C ./data/zhtNewsTopic4_corpus.txt -S ./data/zhtNewsTopic4_sentiDict.txt -m ./result/zhtNewsTopic4_wordOccur.model -r ./result/zhtNewsTopic4_wordOccur.result -c ./result/zhtNewsTopic4_wordOccur.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur PosWordOccur NegWordOccur PosLNeg PosL2Neg NegLPos NegL2Pos PosEqualNeg" -d ./data/zhtNewsTopic4_dataTrain.csv -l ./data/zhtNewsTopic4_seqLabelTrain.csv -D ./data/zhtNewsTopic4_dataTest.csv -L ./data/zhtNewsTopic4_seqLabelTest.csv -C ./data/zhtNewsTopic4_corpus.txt -S ./data/zhtNewsTopic4_sentiDict.txt -m ./result/zhtNewsTopic4_paper.model -r ./result/zhtNewsTopic4_paper.result -c ./result/zhtNewsTopic4_paper.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordCnt" -d ./data/zhtNewsTopic5_dataTrain.csv -l ./data/zhtNewsTopic5_seqLabelTrain.csv -D ./data/zhtNewsTopic5_dataTest.csv -L ./data/zhtNewsTopic5_seqLabelTest.csv -C ./data/zhtNewsTopic5_corpus.txt -S ./data/zhtNewsTopic5_sentiDict.txt -m ./result/zhtNewsTopic5_wordCnt.model -r ./result/zhtNewsTopic5_wordCnt.result -c ./result/zhtNewsTopic5_wordCnt.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur" -d ./data/zhtNewsTopic5_dataTrain.csv -l ./data/zhtNewsTopic5_seqLabelTrain.csv -D ./data/zhtNewsTopic5_dataTest.csv -L ./data/zhtNewsTopic5_seqLabelTest.csv -C ./data/zhtNewsTopic5_corpus.txt -S ./data/zhtNewsTopic5_sentiDict.txt -m ./result/zhtNewsTopic5_wordOccur.model -r ./result/zhtNewsTopic5_wordOccur.result -c ./result/zhtNewsTopic5_wordOccur.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur PosWordOccur NegWordOccur PosLNeg PosL2Neg NegLPos NegL2Pos PosEqualNeg" -d ./data/zhtNewsTopic5_dataTrain.csv -l ./data/zhtNewsTopic5_seqLabelTrain.csv -D ./data/zhtNewsTopic5_dataTest.csv -L ./data/zhtNewsTopic5_seqLabelTest.csv -C ./data/zhtNewsTopic5_corpus.txt -S ./data/zhtNewsTopic5_sentiDict.txt -m ./result/zhtNewsTopic5_paper.model -r ./result/zhtNewsTopic5_paper.result -c ./result/zhtNewsTopic5_paper.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordCnt" -d ./data/zhtNewsTopic6_dataTrain.csv -l ./data/zhtNewsTopic6_seqLabelTrain.csv -D ./data/zhtNewsTopic6_dataTest.csv -L ./data/zhtNewsTopic6_seqLabelTest.csv -C ./data/zhtNewsTopic6_corpus.txt -S ./data/zhtNewsTopic6_sentiDict.txt -m ./result/zhtNewsTopic6_wordCnt.model -r ./result/zhtNewsTopic6_wordCnt.result -c ./result/zhtNewsTopic6_wordCnt.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur" -d ./data/zhtNewsTopic6_dataTrain.csv -l ./data/zhtNewsTopic6_seqLabelTrain.csv -D ./data/zhtNewsTopic6_dataTest.csv -L ./data/zhtNewsTopic6_seqLabelTest.csv -C ./data/zhtNewsTopic6_corpus.txt -S ./data/zhtNewsTopic6_sentiDict.txt -m ./result/zhtNewsTopic6_wordOccur.model -r ./result/zhtNewsTopic6_wordOccur.result -c ./result/zhtNewsTopic6_wordOccur.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur PosWordOccur NegWordOccur PosLNeg PosL2Neg NegLPos NegL2Pos PosEqualNeg" -d ./data/zhtNewsTopic6_dataTrain.csv -l ./data/zhtNewsTopic6_seqLabelTrain.csv -D ./data/zhtNewsTopic6_dataTest.csv -L ./data/zhtNewsTopic6_seqLabelTest.csv -C ./data/zhtNewsTopic6_corpus.txt -S ./data/zhtNewsTopic6_sentiDict.txt -m ./result/zhtNewsTopic6_paper.model -r ./result/zhtNewsTopic6_paper.result -c ./result/zhtNewsTopic6_paper.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordCnt" -d ./data/zhtNewsTopic13_dataTrain.csv -l ./data/zhtNewsTopic13_seqLabelTrain.csv -D ./data/zhtNewsTopic13_dataTest.csv -L ./data/zhtNewsTopic13_seqLabelTest.csv -C ./data/zhtNewsTopic13_corpus.txt -S ./data/zhtNewsTopic13_sentiDict.txt -m ./result/zhtNewsTopic13_wordCnt.model -r ./result/zhtNewsTopic13_wordCnt.result -c ./result/zhtNewsTopic13_wordCnt.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur" -d ./data/zhtNewsTopic13_dataTrain.csv -l ./data/zhtNewsTopic13_seqLabelTrain.csv -D ./data/zhtNewsTopic13_dataTest.csv -L ./data/zhtNewsTopic13_seqLabelTest.csv -C ./data/zhtNewsTopic13_corpus.txt -S ./data/zhtNewsTopic13_sentiDict.txt -m ./result/zhtNewsTopic13_wordOccur.model -r ./result/zhtNewsTopic13_wordOccur.result -c ./result/zhtNewsTopic13_wordOccur.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur PosWordOccur NegWordOccur PosLNeg PosL2Neg NegLPos NegL2Pos PosEqualNeg" -d ./data/zhtNewsTopic13_dataTrain.csv -l ./data/zhtNewsTopic13_seqLabelTrain.csv -D ./data/zhtNewsTopic13_dataTest.csv -L ./data/zhtNewsTopic13_seqLabelTest.csv -C ./data/zhtNewsTopic13_corpus.txt -S ./data/zhtNewsTopic13_sentiDict.txt -m ./result/zhtNewsTopic13_paper.model -r ./result/zhtNewsTopic13_paper.result -c ./result/zhtNewsTopic13_paper.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordCnt" -d ./data/zhtNewsTopic16_dataTrain.csv -l ./data/zhtNewsTopic16_seqLabelTrain.csv -D ./data/zhtNewsTopic16_dataTest.csv -L ./data/zhtNewsTopic16_seqLabelTest.csv -C ./data/zhtNewsTopic16_corpus.txt -S ./data/zhtNewsTopic16_sentiDict.txt -m ./result/zhtNewsTopic16_wordCnt.model -r ./result/zhtNewsTopic16_wordCnt.result -c ./result/zhtNewsTopic16_wordCnt.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur" -d ./data/zhtNewsTopic16_dataTrain.csv -l ./data/zhtNewsTopic16_seqLabelTrain.csv -D ./data/zhtNewsTopic16_dataTest.csv -L ./data/zhtNewsTopic16_seqLabelTest.csv -C ./data/zhtNewsTopic16_corpus.txt -S ./data/zhtNewsTopic16_sentiDict.txt -m ./result/zhtNewsTopic16_wordOccur.model -r ./result/zhtNewsTopic16_wordOccur.result -c ./result/zhtNewsTopic16_wordOccur.stat -a myhcrf -h 3 -i 300 -p 1
./apps/testHCRF/hcrfTest -t -TT -F "WordOccur PosWordOccur NegWordOccur PosLNeg PosL2Neg NegLPos NegL2Pos PosEqualNeg" -d ./data/zhtNewsTopic16_dataTrain.csv -l ./data/zhtNewsTopic16_seqLabelTrain.csv -D ./data/zhtNewsTopic16_dataTest.csv -L ./data/zhtNewsTopic16_seqLabelTest.csv -C ./data/zhtNewsTopic16_corpus.txt -S ./data/zhtNewsTopic16_sentiDict.txt -m ./result/zhtNewsTopic16_paper.model -r ./result/zhtNewsTopic16_paper.result -c ./result/zhtNewsTopic16_paper.stat -a myhcrf -h 3 -i 300 -p 1
